### ISSUE TITLE
Roadmap / todos

### ISSUE THREAD

**Issue by vadimnazarov** [imminfo/hex#1]
- [ ] Implement simple markov chain HLA extractor.
- [ ] Implement preprocessing step.
  - [ ] Filtering.
  - [ ] Error correction.
- [ ] Implement clustering / aligning to DB step.
